# Site settings
title: "codeGlider's blog"
description: "Do not go gentle into that good night..."
baseurl: ""
url: "http://ShyHornet.github.io"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: [ "hard_wrap","autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify","no_intra_emphasis"]

permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "主页"
    url: /
  - title: "关于"
    url: /about
  - title: "简书"
    url: http://www.jianshu.com/users/3007ce57abd3/latest_articles
  - title: "源码"
    url: http://github.com/ShyHornet
  - title: "订阅"
    url: /feed.xml
